# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "Europe/Berlin"
      time: "09:00"
    assignees:
      - "iniva"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    groups:
      testing:
        patterns:
          - "jest"
          - "@jest/*"
          - "ts-jest"
          - "@faker-js/faker"
          - "axios"
          - "@nestjs/testing"
          - "@types/jest"
      linting:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "prettier"
          - "*eslint*"
          - "*prettier*"
          - "typescript-eslint"
      types:
        patterns:
          - "@types/*"
      nestjs:
        patterns:
          - "@nestjs/*"
      passport:
        patterns:
          - "passport"
          - "passport-*"
      drizzle:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
          - "postgres"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "monthly"
      day: "sunday"
      timezone: "Europe/Berlin"
      time: "09:00"
    assignees:
      - "iniva"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
