services:
  api_server:
    build:
      context: ../../
      dockerfile: ./docker/live/Dockerfile
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 5s
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 5s
      timeout: 30s
      retries: 3
    logging:
      driver: none

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dev", "-d", "test" ]
      interval: 1s
      timeout: 3s
      retries: 30
    logging:
      driver: none

  tester:
    build:
      context: ../../
      dockerfile: ./docker/test-integration/Dockerfile
    env_file:
      - .env.test
    volumes:
      - ../../test:/app/test:z
      - ../../src:/app/src:z
      - ../../tsconfig.json:/app/tsconfig.json:z
      - ../../jest.int-config.ts:/app/jest.int-config.ts:z
    depends_on:
      api_server:
        condition: service_healthy
