version: '3.8'
services:
  api_server:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    env_file:
      - .env.test
    volumes:
      - ../../tsconfig.json:/app/tsconfig.json
      - ../../tsconfig.build.json:/app/tsconfig.build.json
    logging:
      driver: none

  tester:
    build:
      context: ../../
      dockerfile: ./docker/test-integration/Dockerfile
    env_file:
      - .env.test
    volumes:
      - ../../test:/app/test
      - ../../src:/app/src
      - ../../dist:/app/dist
      - ../../tsconfig.test-int.json:/app/tsconfig.json
      - ../../jest.int-config.ts:/app/jest.int-config.ts
    depends_on:
      - api_server
