services:
  api_server:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../.:/app/.
    env_file:
      - ../../.env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: develop
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dev", "-d", "develop" ]
      interval: 1s
      timeout: 3s
      retries: 30
    logging:
      driver: none
    ports:
      - '5432:5432'
