name: CI

# This event is triggered on pushes & PRs to all branches
on:
  pull_request:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Preparing pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Cloning repository

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Get npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v3
        name: Setting Node.js Version
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false

  tests:
    needs: prepare
    strategy:
      matrix:
        # Creates jobs for each element in the matrix
        test: ['unit', 'lint', 'typecheck']
      # Let individual jobs in the matrix fail without canceling all jobs
      fail-fast: false
    name: ${{ matrix.test }} tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Cloning repository

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Get npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v3
        name: Setting Node.js Version
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false

      - name: Running ${{ matrix.test }} tests
        run: npm run test:${{ matrix.test }}
        continue-on-error: false

  tests-integration:
    needs: prepare
    name: integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Cloning repository

      - name: Running integration tests
        run: |
          bash docker/test-integration/run.sh
